config/routes.rb
Rails.application.routes.draw do
  resources :imports, only: %i[new create]
  resources :store_transactions, only: %i[index show]
  root :to => "imports#new"
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/recipient.rb
# frozen_string_literal: true

class Recipient < ApplicationRecord
  has_many :transactions, dependent: :restrict_with_exception

  validates :cpf, uniqueness: { case_sensitive: false }
  validates :cpf, presence: true
  validates :cpf, length: { is: 11 }

  validate :cpf_validation

  private

  def cpf_validation
    return if CPF.valid?(cpf)

    errors.add(:cpf, :invalid)
  end
end

app/models/store.rb
# frozen_string_literal: true

class Store < ApplicationRecord
  has_many :transactions, dependent: :restrict_with_exception

  validates :name, uniqueness: true
  validates :name, :owner_name, presence: true
  validates :name, :owner_name, length: { maximum: 50 }
end

app/models/transaction.rb
# frozen_string_literal: true

class Transaction < ApplicationRecord
  belongs_to :recipient
  belongs_to :store
  belongs_to :transaction_type

  validates :date, :amount, :card, :hour, presence: true
  validates :card, length: { maximum: 12 }
  validates :amount, numericality: {
    greater_than: 0,
    less_than_or_equal_to: 99_999_999.99
  }
end

app/models/transaction_type.rb
# frozen_string_literal: true

class TransactionType < ApplicationRecord
  has_many :transactions, dependent: :restrict_with_exception

  enum operation: { credit: 0, debit: 1 }

  validates :kind, :description, :operation, presence: true
  validates :kind, numericality: { only_integer: true }
  validates :description, length: { maximum: 30 }
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/imports_controller.rb
# frozen_string_literal: true

class ImportsController < ApplicationController
  def new; end

  def create
    result = ImportCreateService.perform(params[:file])

    if result.valid?
      redirect_to new_import_path, notice: 'Importação feita com sucesso!'
    else
      redirect_to new_import_path, notice: result.error
    end
  end
end

app/controllers/store_transactions_controller.rb
# frozen_string_literal: true

class StoreTransactionsController < ApplicationController
  def index
    @stores = Store.all
  end

  def show
    @store_transactions = Store.find(params[:id]).decorate
    @balance = StoreBalanceQuery.call(params[:id])
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/imports/new.html.erb
<p class="mt-5">
  Faça o upload de um arquivo de texto CNAB. Veja a descrição do formato necessario ao documento nesse
  <a href="https://github.com/wellison28/cnab-imports">projeto</a>
</p>

<%= form_tag imports_path, enctype: "multipart/form-data", class: "mt-5 border border-secondary p-5", method: :post do %>
  <%= file_field_tag :file, accept: 'text' %>
  <%= submit_tag "Upload", class: "btn btn-primary" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StoreTransactions</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
          <ul class="nav">
            <li class="<%= 'active' if current_page?(new_import_path) %>"><%= link_to "Importar CNAB", new_import_path, class: "font-weight-bold nav-item nav-link" %></li>
            <li class="<%= 'active' if current_page?(store_transactions_path) %>"><%= link_to "Lojas", store_transactions_path, class: "font-weight-bold nav-item nav-link" %></li>
          </ul>
        </div>
      </div>
    </nav>

    <% flash.each do |type, msg| %>
      <div class="alert alert-warning alert-dismissible fade show" role="alert">
        <%= msg %>
      </div>
    <% end %>

    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/store_transactions/index.html.erb
<table class="table table-secondary table-hover">
  <thead class="">
    <tr>
      <th scope="col">#</th>
      <th scope="col">Nome</th>
      <th scope="col">Responsável</th>
    </tr>
  </thead>
  <tbody>
    <% @stores.each_with_index do |store, index| %>
        <tr>
          <td><%= index+1 %></td>
          <td><%= link_to store.name, store_transaction_path(store) %></td>
          <td><%= store.owner_name %></td>
        </tr>
    <% end %>
  <tbody>
</table>

app/views/store_transactions/show.html.erb
<h2>
<span class="badge badge-info">Saldo: <%= number_to_currency(@balance, unit: "R$ ", separator: ",", delimiter: ".") %></span>
</h2>

<table class="table table-secondary table-hover">
  <thead>
    <tr>
      <th scope="col" class="text-center">Tipo</th>
      <th scope="col" class="text-center">Data</th>
      <th scope="col" class="text-center">Valor</th>
      <th scope="col" class="text-center">CPF</th>
      <th scope="col" class="text-center">Cartão</th>
      <th scope="col" class="text-center">Hora</th>
      <th scope="col" class="text-center">Dono da Loja</th>
      <th scope="col" class="text-center">Nome da Loja</th>
    </tr>
  </thead>
  <tbody>
  <% @store_transactions.transactions.each do |transaction| %>
    <tr>
      <td><%= transaction.transaction_type.description %></td>
      <td><%= transaction.date %></td>
      <td><%= number_to_currency(transaction.amount, unit: "R$ ", separator: ",", delimiter: ".") %></td>
      <td><%= transaction.recipient.cpf %></td>
      <td><%= transaction.card %></td>
      <td><%= transaction.hour %></td>
      <td><%= transaction.store.owner_name %></td>
      <td><%= transaction.store.name %></td>
    </tr>
  <% end %>
</table>